### PR TITLE
bin command line utitlity should be unique (it was deploy.rb)

### PR DESCRIPTION
**Pull request by j1n6**
I suggest to rename the `deploy.rb` to the same name as the gem.
This way I can execute `marathon_deploy` as command line tool instead of `deploy.rb`(a bit misleading)

### CODE REVIEW

**Comment by j1n6** [comment]
Just tested locally, seems to work well

**Comment by sielaq** [comment]
can you also remove from other scripts `.rb` extension so it will be more consistent ?

**Comment by j1n6** [comment]
Will do. Thanks.

**Comment by joncolby** [comment]
I agree.  thanks for the suggestion and patch!

**Comment by j1n6** [comment]
I had a look at the other two rb script, I think they should be a command line option for the marathon_deploy command, and those two files should be internal libs out side the bin directory.

**Comment by joncolby** [comment]
Hi Jim,

I would agree that one executable would probably be cleaner (and is probably the Ruby gem standard way).  My motivation was to keep the main executable simple for the end user to understand and use.   The other helper scripts are used in our build pipeline already.

I’ll keep your suggestion in mind as we develop the tool further.   Pretty swamped at the moment though.

**Comment by j1n6** [comment]
Totally understood your concern. I was going to develop similar tool for our company, glad you have done the work for us!

**Pull request merged**
